# Generated by Django 6.1.1 on 2026-09-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_categoria_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Ropa', 'Ropa'), ('Hogar', 'Hogar'), ('Electrónica', 'Electrónica')], max_length=50),
        ),
    ]
