# Generated by Django 6.1.1 on 2026-09-30 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Hogar', 'Hogar'), ('Electrónica', 'Electrónica'), ('Ropa', 'Ropa')], max_length=50),
        ),
    ]
